# -*- coding: utf-8 -*-edu
"""
/***************************************************************************
 seg2shp
                                 A QGIS plugin
 This plugin performs semantic segmentation and convert it to shape file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-11
        copyright            : (C) 2023 by Hansae Kim
        email                : kim4012@purdue.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load seg2shp class from file seg2shp.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .seg2shp import seg2shp
    return seg2shp(iface)
